import Head from "next/head";
import { useEffect, useState } from "react";

import Container from "../components/Container";
import styles from "../styles/Home.module.css";
import Wrapper from "../components/Wrapper";
import Submit from "../components/Submit";
import TodoContext from "../store/todo-context";
import useTask from "../hook/useTask";

export default function Home() {
  const [enteredTodo, setEnteredTodo] = useState();

  useEffect(() => {
    const getTasks = async () =>
      await fetch("/api/list-todos")
        .then(async (res) => {
          return await res.json();
        })
        .then((datas) => {
          console.log(datas.data);
          setEnteredTodo(datas.data);
        });
    getTasks();
  }, []);

  const addTaskHandler = async (task) => {
    await fetch("/api/add-todos", {
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      method: "POST",
      body: JSON.stringify({
        todo: task,
      }),
    });

    await fetch("/api/list-todos")
      .then(async (res) => {
        return await res.json();
      })
      .then((datas) => {
        setEnteredTodo(datas.data);
      });
  };

  const deleteTaskHandler = async (id) => {
    const url = `/api/delete-todos/${id}`;

    await fetch(url, {
      headers: {
        "Content-Type": "application/json",
      },
      method: "POST",
    });

    const arrayAfterDelete = enteredTodo.filter((todo) => todo.id !== id);
    setEnteredTodo(arrayAfterDelete);
  };

  return (
    <TodoContext.Provider value={{ addTaskHandler, deleteTaskHandler }}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          />
        </Head>
        <Container className="container">
          <Submit />

          <div className="task-list">
            {enteredTodo && <Wrapper todoData={enteredTodo}></Wrapper>}
            {/* {enteredTodo && <Wrapper todoData={enteredTodo}></Wrapper>} */}
          </div>
        </Container>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.10.2/Sortable.min.js"></script>
      </div>
    </TodoContext.Provider>
  );
}

// import Head from "next/head";
// import { useEffect, useState } from "react";

// import Container from "./components/Container";
// import styles from "../styles/Home.module.css";
// import Wrapper from "./components/Wrapper";
// import Submit from "./components/Submit";

// export default function Home() {
//   const [enteredTodo, setEnteredTodo] = useState();

//   useEffect(async () => {
//     await fetch("/api/list-todos")
//       .then(async (res) => {
//         return await res.json();
//       })
//       .then((datas) => {
//         console.log(datas.data);
//         setEnteredTodo(datas.data);
//       });
//   }, []);

//   const addTaskHandler = async () => {
//     await fetch("/api/list-todos")
//       .then(async (res) => {
//         return await res.json();
//       })
//       .then((datas) => {
//         setEnteredTodo(datas.data);
//       });
//   };

//   const deleteTaskHandler = (id) => {
//     const arrayAfterDelete = enteredTodo.filter((todo) => todo.id !== id);
//     setEnteredTodo(arrayAfterDelete);
//   };

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//         <link
//           rel="stylesheet"
//           href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
//         />
//       </Head>
//       <Container className="container">
//         <Submit setAddTask={addTaskHandler} />
//         <div className="task-list">
//           {enteredTodo && (
//             <Wrapper
//               todoData={enteredTodo}
//               deleteTask={deleteTaskHandler}
//             ></Wrapper>
//           )}
//         </div>
//       </Container>
//       <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.10.2/Sortable.min.js"></script>
//     </div>
//   );
// }
