import Head from "next/head";
import { useEffect, useState } from "react";

import Container from "./components/Container";
import styles from "../styles/Home.module.css";
import Wrapper from "./components/Wrapper";
import Submit from "./components/Submit";

export default function Home() {
  const [enteredTodo, setEnteredTodo] = useState();

  useEffect(async () => {
    await fetch("http://localhost:8888/list-todos")
      .then(async (res) => {
        return await res.json();
      })
      .then((datas) => {
        console.log(datas.data);
        setEnteredTodo(datas.data);
      });
  }, []);

  const addTaskHandler = async (newTodo) => {
    await fetch("http://localhost:8888/list-todos")
      .then(async (res) => {
        return await res.json();
      })
      .then((datas) => {
        setEnteredTodo(datas.data);
      });
  };

  const deleteTaskHandler = (id) => {
    const arrayAfterDelete = enteredTodo.filter((todo) => todo.id !== id);
    setEnteredTodo(arrayAfterDelete);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>
      <Container className="container">
        <Submit setAddTask={addTaskHandler} />
        <div className="task-list">
          {enteredTodo && (
            <Wrapper
              todoData={enteredTodo}
              deleteTask={deleteTaskHandler}
            ></Wrapper>
          )}
        </div>
      </Container>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.10.2/Sortable.min.js"></script>
    </div>
  );
}
