import Head from "next/head";
import { useEffect, useState } from "react";

import Container from "./components/Container";
import styles from "../styles/Home.module.css";
import Wrapper from "./components/Wrapper";
import axios from "axios";

export default function Home() {
  const [enteredTodo, setEnteredTodo] = useState();

  useEffect(async () => {
    await axios.get("http://localhost:8080/list-todos").then((res) => {
      setEnteredTodo(res.data);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container className="container">
        <form>
          <input type="text" name="todo" />
          <button type="submit" id="submit" className="submitBtn">
            SUBMIT
          </button>
        </form>
        <Wrapper todoList={enteredTodo}></Wrapper>
      </Container>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.10.2/Sortable.min.js"></script>
    </div>
  );
}
