import Head from "next/head";

import Container from "../components/Container";
import styles from "../styles/Home.module.css";
import Wrapper from "../components/Wrapper";
import Submit from "../components/Submit";
import TodoContext from "../store/todo-context";
import useTask from "../hooks/useTask";

export default function Home() {
  const [
    tasks,
    addTaskHandler,
    editTaskHandler,
    deleteTaskHandler,
    handleDragEnd,
  ] = useTask();

  return (
    <TodoContext.Provider
      value={{
        addTaskHandler,
        editTaskHandler,
        deleteTaskHandler,
        handleDragEnd,
      }}
    >
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          />
        </Head>
        <Container className="container">
          <Submit />

          <div className="task-list">
            {tasks && <Wrapper tasks={tasks}></Wrapper>}
          </div>
        </Container>
      </div>
    </TodoContext.Provider>
  );
}
